version: '3.8'

services:

  db:
    image: postgres
    environment: 
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  api:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment: 
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_HOST=${DATABASE_HOST}
    volumes:
      - ./api:/api
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    command: ['yarn', 'serve']
    depends_on:
      - api