name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  api:
    runs-on: ubuntu-latest
    env:
        DATABASE_PASSWORD: postgres
        DATABASE_USERNAME: postgres
        DATABASE_HOST: db
        POSTGRES_PASSWORD: postgres
    steps:
          
      - uses: actions/checkout@v2

      - name: build api containers
        run:  docker-compose up --no-start api

      - name: create database
        run:  docker-compose run api rake db:create
        
      - name: run migrate
        run:  docker-compose run api rake db:migrate

      - name: run api tests
        run : docker-compose run api bundle exec rails test
        
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: build client container
        run: docker-compose up --no-start client
        
      - name: run client tests
        run:  docker-compose run client yarn run test:unit
    
